# Generated by Django 6.0 on 2026-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_pictures/'),
        ),
    ]
